<?php


namespace View\Html;


class TableCancel extends Table
{
    public function data(array $data)
    {
        return parent::data($data); // TODO: Change the autogenerated stub

        $str = "";

        foreach ($data as $row) {
            $str .= "\t<tr>\n";
            foreach ($row as $cell) {
                $str .= "\t\t<td>$cell</td>\n";
            }
            $str .= "\t\t<td>" .
                "<a role='button' href='?action=&type=$this->type&id=$row[id]' class='btn btn-primary'>" .
                "Отменить заказ</a></td>\n";
        }
        $this->data = $str;
        return $this;
    }

}