<?php


namespace Controller;

use View\View;
use Core\Config;

class CurrentUserOrdersController extends OrdersController
{
    public function __construct(View $view)
    {
        parent::__construct($view);
        $this
            ->view
            ->setFolder("currentuserorders");
    }

    public function actionShow(array $data)
    {
        $this
            ->view
            ->setTemplate('show')
            ->setData([
                "user_id" => $_SESSION['user']['id'],
                "usersList" => $this->usersTable->getUsers(),
                "dishesList" => $this->dishesTable->getDishes(),
                'table' => $this
                    ->table
                    ->reset()
                    ->setPageSize(Config::PAGE_SIZE)
                    // ->addWhere("`orders`. `users_id` = " . $_SESSION['user']['id'])
                    ->getOrdersPageUserFilter($data['get']['page'] ?? 1, $_SESSION['user']['id']),
                'fields' => array_diff($this->table->getColumnsNames(), ['id']),
                'comments' => $this->table->getColumnsComments(),
                'type' => $this->getClassName(),
                'pageCount' => $this->table->pageCount()
            ]);
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data); // TODO: Change the autogenerated stub

        $this
            ->view
            ->setFolder('currentuserorders');
    }

    // добавление заказа
    public function actionAddOrder(array $data)
    {
//        print_r($data);
//        print_r($_SESSION);
        $users_id = $_SESSION['user']['id'];
        $dishes_id = $data['get']['id'];

        $this->table->getAddOrders($users_id, $dishes_id);
        $this->redirect('?action=show&type=currentuserorders');
    }
}
