<?php


namespace Controller;

use View\View;
use Core\Config;

class CurrentUserOrdersController extends OrdersController
{
    public function __construct(View $view)
    {
        parent::__construct($view);
        $this
            ->view
            ->setFolder("currentuserorders");
    }

    public function actionShow(array $data)
    {


        // parent::actionShow($data); // TODO: Change the autogenerated stub

        //        print_r($_SESSION);

        //             ->addData(
        //                 [
        //                     
        //                     "usersList" => $this->usersTable->getUsers(),
        // //                "dishesList" => $this->dishesTable->getDishes(),
        //                     'table' => $this
        //                         ->table
        //                         ->reset()
        //                         ->setPageSize(Config::PAGE_SIZE)
        //                         ->getOrdersPageUserFilter(
        //                             $data['get']['page'] ?? 1,
        //                             $_SESSION['user']['id']
        //                         )
        //                 ]
        //             );

        $this
            ->view
            ->setTemplate('show')
            ->setData([
                "user_id" => $_SESSION['user']['id'],
                "usersList" => $this->usersTable->getUsers(),
                "dishesList" => $this->dishesTable->getDishes(),
                'table' => $this
                    ->table
                    ->reset()
                    ->setPageSize(Config::PAGE_SIZE)
                    // ->addWhere("`orders`. `users_id` = " . $_SESSION['user']['id'])
                    ->getOrdersPageUserFilter($data['get']['page'] ?? 1, $_SESSION['user']['id']),
                'fields' => array_diff($this->table->getColumnsNames(), ['id']),
                'comments' => $this->table->getColumnsComments(),
                'type' => $this->getClassName(),
                'pageCount' => $this->table->pageCount()
            ]);
    }
}
