<?php

namespace Controller;

use Core\Config;

class DishesManagerController extends DishesController
{

    protected  $tableName = "dishes";

    public function __construct($view)
    {
        parent::__construct($view);

        $this->view->setFolder('dishesmanager');
    }

    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub
        $this
            ->view
            ->setTemplate('managerShow')
            ->setData([
                'table' => $this
                    ->table
                    ->reset()
                    ->setPageSize(Config::PAGE_SIZE_DISH)
                    ->getPage($data['get']['page'] ?? 1),
                'fields' => array_diff($this->table->getColumnsNames(), ['id']),
                'comments' => $this->table->getColumnsComments(),
                'type' => $this->getClassName(),
                'pageCount' => $this->table->pageCount()
            ]);
    }

    public function actionAdd(array $data)
    {

    }

    public function actionEdit(array $data)
    {

    }

    public function actionDel(array $data)
    {

    }
}
