<?php


namespace Controller;


use Core\Config;

class ManagerOrdersController extends OrdersController
{
    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub

//        print_r($_SESSION);
        $this
            ->view
            ->setFolder("managerorders")
            ->addData(
                [
                    "user_id" => $_SESSION['user']['id'],
                    "usersList" => $this->usersTable->getUsers(),
//                "dishesList" => $this->dishesTable->getDishes(),
                    'table' => $this
                        ->table
                        ->reset()
                        ->setPageSize(Config::PAGE_SIZE)
                        ->getOrdersPageUserFilter(
                            $data['get']['page'] ?? 1,
                            $_SESSION['user']['id']
                        )
                ]
            );
    }
}